### ISSUE TITLE
Regarding Wombat fetch from solr Mysql

### ISSUE THREAD

**Issue by kalpanadare** [PLOS/wombat#1284]
Hi All,

I need some clarification regarding plos - Content Repo, Rhino and Wombat.
I updated all these projects and uploading of zip works fine. Now i am unable to fetch those data from solr while doing Advanced Search from Wombat. 

I would like to know how solr connects to Mysql and fetch data. Is there any separate configuration for it? 

And there is a update of JournalCollection and PreprintCollection. what would be the value of it in Wombat.yaml file? 

Please do help. Awaiting for your response.

**Comment by sjtower** [comment]
Hi @kalpanadare ,

I'm sorry it took us so long to respond. We are still working out how to help our open-source users.

Solr does not connect to MySql directly to fetch data. Instead, you have to index individual article XML to solr using the /update endpoint. I'm afraid I can't get into the specifics here but solr has pretty good documentation [here](https://lucene.apache.org/solr/guide/6_6/indexing-and-basic-data-operations.html)

The wombat.yaml file has been updated, but we forgot to update the open source documentation. We will do this, but in the meantime here is my wombat.yaml for reference:

server: http://localhost:8123/
# URL of the server for the service API ("Rhino")

themeSources:
  - type: filesystem
    path: /home/stower/plos-themes
# Location of the plos-themes directory

solr:
  url: http://localhost:8983/solr/
  journalsCollection: collection1
  preprintsCollection: preprints
# solrServer: http://localhost:8983/solr/collection1/select/
# solrServer: http://solr-220.soma.plos.org:8983/solr/test/select/
# URL of the Solr server.

compiledAssetDir: /home/stower/compiled-assets
# The local directory to which to write compiled JavaScript and CSS assets.
#
# If null, JavaScript and CSS code will not be compiled, so it will show up
# unminified for "dev mode".

httpConnectionPool:
  maxTotal:           100
  defaultMaxPerRoute: 100
# Values for HTTP connection management. Setting these too low can cause
# serious performance degradation. For details, see
# org.apache.http.impl.conn.PoolingHttpClientConnectionManager,
# http://hc.apache.org/httpcomponents-client-ga/tutorial/html/connmgmt.html

cache:
  memcachedHost: null
  memcachedPort: null
  cacheAppPrefix: null
# Parameters for Memcached. Set all to null to disable Memcached. Otherwise,
# all three are required.

cas:
  casUrl: https://register.plos.org/cas
  loginUrl: https://register.plos.org/cas/login
  logoutUrl: https://register.plos.org/cas/logout

commentsDisabled: False
# Set to true to disable comment creation
